### ISSUE TITLE
Multilingual causes notifications to be sent in the language of the person who caused the notification

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/addons#155]
If you post a thread and star it, and I switch to French and post in your thread, you will receive the notification (on the forum and by e-mail) in French rather than the language of your choice.

**Comment by linc** [comment]
This is a verified, bonafide PITA.

**Comment by JasonBarnabe** [comment]
I looked at this a bit. It's easy enough to figure out the proper locale for the person you're sending to, but there doesn't seem to be a facility for loading a string in a different locale than the current user's. `Gdn_Locale` says it's a singleton and presumably gets initialized with the current user's locale at the start of the request. Do you have any idea how that aspect would work?

**Comment by bleistivt** [comment]
Gdn_Locale is used as a singleton, but it doesn't implement the singleton interface and the constructor is public, so you can create new instances:
https://github.com/vanilla/vanilla/blob/master/bootstrap.php#L212

**Comment by initvector** [comment]
Unfortunately, this isn't something we can take immediate action on.  This is going to require some significant changes to the way we handle translations and notifications.

The primary problem is as follows:
These types of notification emails Vanilla sends are based off records in the Activity table.  When activities are added by applications or plug-ins, their `Headline` and `Story` fields are populated with translated values.  We lose the original translation slug and we can't translate something that's already been translated.  We don't really have a way of hooking in before these activity entries are created with the translated strings, since they're sprinkled all throughout the code with the translated strings already a part of their parameters.

We're planning to incorporate the capabilities of the Multilingual plug-in into core Vanilla.  Addressing this issue will be a part of that process.  Unfortunately, I can't give a timeline, but it is on the roadmap.
