### ISSUE TITLE
GooglePlus: Error on login

### ISSUE THREAD

**Issue by franga2000** [vanilla/addons#163]
Hi, I'm getting an error when a user tries to log in with Google+. 

When I connect with G+ it asks me to choose a username for the forum and when I submit it, I get an error page saying "**Something has gone wrong**". 
The user is put into the database like so:

Name | Password | HashMethod | Photo | Email
------------- | ------------- | ------------- | ------------- | -------------
*&lt;chosen username&gt;* | *&lt;random letters and numbers (not a hash)&gt;* | "Random" | *&lt;google+ photo&gt;* | *&lt;gmail adress&gt;*

It seems like the user info is written into the database just fine but for some reason a random password is set. 
The next time I try to log in with G+ it says I already have an account and asks for the pasword but whetever I put in, it always says "**Your account does not have a password assigned to it yet. Click here to reset your password.**" 

There's nothing in apache's error log and I have all required modules enabled (as far as I know).
I quckly looked through the plugin code but I've never used the Vanilla API so I couldn't find the problem.

**Comment by linc** [comment]
That Gdn_User record entry is correct. It sounds like what's happening is your GDN_UserAuthentication record is not being created correctly, probably because it got stopped between creating the account and actually authenticating. To get a full error message enable [debug mode](http://docs.vanillaforums.com/developer/troubleshooting/) on your side. I recommend using the [community forum](https://vanillaforums.org/discussions) to assist in your troubleshooting. They can often assist with narrowing down a technical issue, whether it's in your server config or the product.
