### ISSUE TITLE
jsConnect: when signing in via jsConnect user still needs to enter password first time

### ISSUE THREAD

**Issue by eitzenbe** [vanilla/addons#181]
I have vanilla integrated with our website from dragonteam.net. It kinda works, BUT
the user is required to enter the password ONCE ... Is this a misconfig on my side or a "feature"?

Also I am using the comments view as embedded div popup and whenever a user is forwarded to the signin page it will force a reload/redirect of the whole page to the comments page....

I am in the process of getting this onto our demo site next week probably, then you can see it in "action"

But maybe there is something obvious I didnt take care of?

**Comment by linc** [comment]
To force it to auto-connect without requiring a password, set `Garden.Registration.AutoConnect = TRUE` in the config. http://docs.vanillaforums.com/developers/configuration/

To auto sign in users, send then thru the endpoint `/sso` which will auto-call your SSO endpoint. Example: `yourforum.com/sso?Target=/discussions` will pop them thru SSO and land on the discussions page in 1 step. You'd put that link in your nav instead of a direct link to the forum homepage.

It also sounds like you want to set `Garden.SignIn.Popup = FALSE` to fix the embedded comments signin conflict.

If you need some more assistance with this, use the open source community at http://vanillaforums.org/discussions

Cheers!
