### ISSUE TITLE
Advanced Editor & QnA: Editing answer gets you stuck in edit mode

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/addons#386]
**Steps to reproduce:**

1. Post a new Question. 
2. Reply to the question 
3. Mark the reply as the "Answer" - that Answer is now currently displayed both at the beginning, right after the initial question as well as in-line in the discussion) 
4. Go and Edit the original Answer reply (i.e. the inline version of it, not the duplicate one displayed after the question) 
5. Make a change in the text and Save 

**Observed result:**

The change is saved, but now the editing box is duplicated and only disappears after refresh. 

**Expected result:**

The change is saved and the post reverts from the editing state.

**Comment by initvector** [comment]
*Note: To recreate this issue, you'll need to make sure `QnA.AcceptedAnswers.Filter` is set to `false`.*

**Comment by initvector** [comment]
The problem is when the answer is displayed at the top and in-line with the other comments, it creates two elements with the same ID.  Any element with an ID attribute is supposed to be unique.  If you're using JavaScript to query the DOM for an element with an ID of "Comment_1", and you have two elements with that ID, it's only going to grab the first one.  We're only affecting change on the first element, which doesn't even need it in this case.
