### ISSUE TITLE
[Pockets] Increase the maximum number of characters that a pocket can hold

### ISSUE THREAD

**Issue by charrondev** [vanilla/addons#545]
When doing a custom theme for a client who wants to use their header/footer wholesale, but does not have theme pull (not a VIP), we normally stick it in a Pocket. Some clients have reached the limit of the Pocket now though (the `Body` column's type is `TEXT`) and are having to split their Pockets into 2 parts. This can present issues as there is a delay between changing the 2 separate Pockets and the page can be broken in between.

Unless we enlarge the maximum size of a Pocket, we will have to point these clients to the `CustomTheme` plugin, which is not ideal and makes future development harder for us.

I propose changing the type of the `Body` to `MEDIUMTEXT`. I'm not really sure how DB migrations work for addons, but any explanation would be appreciated.

Thoughts @linc

**Comment by DaazKu** [comment]
My opinion on this is that they are probably using pockets the wrong way. 65535 characters PER POCKET should be more than enough.

**Comment by tburry** [comment]
Although I agree with Alex, I think a bump is going to be fine. Custom theme needs to allow large text and the line between pockets and custom theme is getting increasingly blurred. What we'll have to watch out for is stuff like caching if we ever decide to do that with pockets.

**Comment by Charrondev** [comment]
The best practices way to manage a header as large as this one and integrate it into a vanilla theme is to check it into version control and update it through their, but that option is only available for VIP clients on infrastructure.

**Comment by chrisvanpatten** [comment]
(Please feel free to delete this if I'm pushing too far off topic… Still getting a sense of what's appropriate/not appropriate for these threads!)

Out of curiosity, what would be the disadvantage of putting that header into the custom theme vs the pocket? Is it primarily so clients can edit that specific portion of the header/footer more easily?

Something we've done in the past to keep from overstuffing Pockets is to have the full headers/footers be in the custom theme, and then isolate out specific areas that we'd expect the client to want to manage (such as nav links or legal fine print or what-not) as individual Pockets with custom locations. That tends to save clients from needing to edit in the CustomTheme area directly, and also makes it a little easier to manage the pocket because they don't have to scroll through lots of arbitrary HTML.

(A pretty good example of where we did this on the hosted infrastructure is the [FreedomPop theme](https://forums.freedompop.com/us/).)

**Comment by Charrondev** [comment]
Often it can be better to put the core of the header into the theme itself and have individual pockets for different sections of it if its around the right size. That can even be necessary if the header requires forum specific content. Some headers (especially in responsive themes) contain critical forum navigation, and forum specific content. If you want to include built in or custom modules though you can't put that logic in pocket, because pockets don't currently support templating engines.

So generally the structure is:
- Most of the header in the theme itself
- Some parts of it in pockets. Good candidates for this are sections that are frequently updated, or if you would to have certain sections labelled to make it easier for clients to find

Putting the header in Customize Theme can painful if:
- the core theme lives in version control (this the case for VIP clients or clients that have custom services fulfilled directly by Vanilla) reconciling changes between what lives in version control and what lives in the custom theme can be difficult. There is diff viewer for the customize theme, which can make it difficult to figure out exactly what has changed. Its like doing a 3-way git merge, except you don't have the tooling to do it easily.
- You want to maintain a clear separation between your code and the clients code.
- The header is a massive size (In this case thousands of lines of content with nested subnavigation, and thousands of lines of CSS). The client has a massive, huge, ready-made, and polished header that they would like to update frequently. It does not contain any vanilla specific components in it. Those components live in a seperate sub header.

Especially if the amount of frequently changing content dwarfs the `default.master.tpl` (primary view you see in customize theme), it makes it much more difficult for the client to make changes. You can ignore a major source of programming error by separating this into its own pocket.

**Comment by DaazKu** [comment]
Let's add a validation that won't let you save if you bust the new limit.
