### ISSUE TITLE
SteamConnect "UniqueID is required" 

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/addons#647]
![image](https://user-images.githubusercontent.com/7501633/43745355-e1e6ffb0-99a3-11e8-9411-0db304fb4895.png)

Connecting steam is just pasting your API key into the settings, so theres not much a user could do to debug. I replicated this on my demo: 
![image](https://user-images.githubusercontent.com/7501633/43745390-0c048f56-99a4-11e8-96bf-88fcd465a766.png)

The steam app gives no feedback on what might be wrong, and we have no instructions on what needs to go on into the "domain" settings on the stream side. I revoked my API key and got the same error. I put in a new one and got the same error.

**Comment by linc** [comment]
Acceptance criteria

* Investigate this error and determine root cause
* Determine and implement the fix OR cite why a fix is not possible (e.g. they no longer support SSO).
* Fix inline docs.
* Fix coding standards issues.
* Write brief README that references Steam docs.
* Add a brief entry for the addon to our public docs.

**Comment by linc** [comment]
If Steam has radically changed their SSO implementation, we should deprecate this addon and present v2 as a service for Daybreak.
