### ISSUE TITLE
Failed stopping measure 'controller' because it hasn't been started

### ISSUE THREAD

**Issue by Kaspar-K** [vanilla/addons#710]
Debugbar 1.4.1
Updated from 2.8.1 to 2.8.3

Trying to enable debugbar returns message "Failed stopping measure 'controller' because it hasn't been started"
Debug Bar gets enabled anyway - but it is not shown until plugin-page is reloaded.

Have deleted cache, run /utility/update, disabled plugins, changed them to keystone - same message occour.
Have had Debug Bar enabled on 2.8.1 - no message.

**Comment by charrondev** [comment]
I've definitely seen this myself at some point so I would accept contributions that fix the message.

This plugin was moved out of core and into this repo however, because it's not really actively used by our team anymore due to a few issues

- It doesn't work anything except `Gdn_Controller`, which we have been actively working to replace for the past 2 years. That means it doesn't work with APIv2 and it does not work with new `Vanilla\Web\Page` controller & routing that we've been working on this year.
- It wasn't actually that precise for measuring performance issues.
- This isn't an area where we are able to add a lot of value.

As a team we've moved to using [Blackfire](https://blackfire.io/my/profiles), which is a really awesome tool.

**Comment by Kaspar-K** [comment]
"This plugin was moved out of core and into this repo however, because it's not really actively used by our team anymore due to a few issues"

Oh, it recently became open source. Assumed it was still used.

https://open.vanillaforums.com/discussion/36993/addons-security-updates-sunset-announcements

**Comment by Kaspar-K** [comment]
Just noticed this
https://github.com/vanilla/addons/issues/688

**Comment by charrondev** [comment]
Yeah. I was the one that moved it. I think the main reason it wasn't open sourced to begin with was because it was a hacky internal tool.

Some of our dev determined that we needed more robust tooling to take performance seriously. Unfortunately if you're just a lone developer Blackfire is quite pricy, but if you work professionally in PHP it's definitely useful.

As I said, if someone in the community is interested in adding to this tool I can answer some questions if you hit a wall, but I can't really dedicate much time myself to it.

**Comment by R-J** [comment]
I know a way to prevent that message, but I do not know if that's a solution or a dirty workaround. The problem comes up here:

~~~
    public function base_render_before($sender) {
        static $called = false;

        if ($called) {
            return;
        }

        $bar = $this->debugBar();
        $bar['time']->stopMeasure('controller');
~~~

The measuring never begun and therefore the TimeDataCollector throws the error message.

My approach simply wouldn't try to stop anything if nothing has been started:

~~~
        $bar = $this->debugBar();
        if ($bar['time']->hasStartedMeasure()) {
            $bar['time']->stopMeasure('controller');
        }
~~~

But I cannot tell if there are situations where that error would be a good hint and my workaround would surpress it, making it even harder to debug something...

Maybe instead of throwing the error simply displaying a popup message would be enough. My personal opinion is that a debugging tool should inform you and not break your code.
